'use strict';
const KEY='aula-al-dia-v1';
const uid=()=>crypto.randomUUID();
const copy=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const defaults=()=>['Tarea del día','Autoevaluación','Ev. del profe'].map(name=>({id:uid(),name,states:['yes','part','no']}));
const states={empty:{symbol:'○',label:'Sin marcar',cls:'blank'},yes:{symbol:'✓',label:'Logrado',cls:'good'},part:{symbol:'~',label:'En proceso',cls:'progress'},no:{symbol:'✕',label:'No logrado',cls:'no'}};
let db={version:1,courses:[]},loadFailed=false,saveFailed=false;
try{const raw=localStorage.getItem(KEY);if(raw){db=JSON.parse(raw);if(db.version!==1||!Array.isArray(db.courses))throw Error('Formato desconocido')}}catch(e){loadFailed=true;db={version:1,courses:[]}}
let courseId=null,sessionId=null,view='grid',studentIndex=0,projection=false,toastTimer;
const app=document.getElementById('app'),modal=document.getElementById('modal');
const course=()=>db.courses.find(c=>c.id===courseId);
const session=()=>course()?.sessions.find(s=>s.id===sessionId);
const readonly=()=>!!session()&&session().date!==today();
function save(){if(window.AulaCloud)return window.AulaCloud.save();if(loadFailed)return false;try{localStorage.setItem(KEY,JSON.stringify(db));saveFailed=false;return true}catch(e){saveFailed=true;toast('No se pudo guardar. Mantén esta página abierta y libera espacio en el navegador.');return false}}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),5000)}
function dialog(title,body,onSubmit){modal.innerHTML=`<form><div class="row"><h2>${title}</h2><button type="button" data-close aria-label="Cerrar">✕</button></div>${body}<p class="error" id="form-error" role="alert"></p><div class="modal-actions"><button type="button" data-close>Cancelar</button><button class="primary" type="submit">Guardar</button></div></form>`;modal.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal.close());modal.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.target))};modal.showModal()}
const formError=t=>modal.querySelector('#form-error').textContent=t;
function render(){document.body.classList.toggle('projection',projection);app.innerHTML=`${saveFailed?'<div class="save-error" role="alert">No se ha guardado el último cambio. <button data-action="retry">Reintentar guardado</button></div>':''}<header class="topbar"><div class="brand"><span class="mark">✓</span>Aula al día</div><span class="local">${loadFailed?'Guardado no disponible':saveFailed?'Cambios sin guardar':'Guardado en este navegador'}</span></header><main class="wrap">${loadFailed?'<div class="empty"><h1>No pudimos leer tus datos</h1><p>No los hemos reemplazado. Prueba abrir la aplicación en el navegador donde guardaste tus cursos o revisar el almacenamiento del navegador.</p><button onclick="location.reload()">Volver a intentar</button></div>':course()?renderCourse():renderHome()}</main>`}
function renderHome(){return `<div class="row intro"><div><div class="eyebrow">Tu espacio de clase</div><h1>Mis cursos</h1><p>Cada clase, un nuevo comienzo.</p></div><button class="primary large" data-action="new-course">+ Crear curso</button></div>${db.courses.length?`<div class="cards">${db.courses.map(c=>`<button class="course-card" data-action="open-course" data-id="${c.id}"><span class="pill">${c.students.length} estudiantes</span><span class="course-name">${esc(c.name)}</span><span class="hint">${c.sessions.length} ${c.sessions.length===1?'clase registrada':'clases registradas'} · Abrir curso</span></button>`).join('')}</div>`:`<section class="empty"><div class="emblem">✓</div><h2>Tu primera clase empieza aquí</h2><p>Crea un curso y pega la lista de estudiantes.<br>Después, solo genera la clase y marca sus avances.</p><button class="primary large" data-action="new-course">+ Crear mi primer curso</button></section>`}<p class="footnote">Tus cursos e historial se guardan en tu cuenta. Descarga un respaldo cuando lo necesites.</p>`}
function renderCourse(){const c=course(),s=session();return `<div class="breadcrumb"><button class="quiet" data-action="home">Mis cursos</button> <span class="hint">/ ${esc(c.name)}</span></div><div class="row course-head"><div><div class="eyebrow">${s?'Seguimiento de clase':'Listo para una nueva clase'}</div><h1>${esc(c.name)}</h1><span class="hint">${s?s.students.length:c.students.length} estudiantes${s?' · '+dateLabel(s.date):''}</span></div><div class="actions"><button data-action="edit-course">Editar curso</button><button data-action="criteria">Criterios del curso</button><button data-action="project">${projection?'Salir de proyección':'⛶ Proyectar'}</button><button class="primary large" data-action="generate">${c.sessions.some(x=>x.date===today())?'Abrir clase de hoy':'+ Generar clase de hoy'}</button></div></div><div class="row"><div class="tabs" aria-label="Vistas"><button data-action="view" data-view="grid" class="${view==='grid'?'active':''}" aria-pressed="${view==='grid'}">▦ Grilla</button><button data-action="view" data-view="student" class="${view==='student'?'active':''}" aria-pressed="${view==='student'}">Por estudiante</button><button data-action="view" data-view="history" class="${view==='history'?'active':''}" aria-pressed="${view==='history'}">Historial <span class="hint">${c.sessions.length}</span></button></div>${s&&view!=='history'&&view!=='student-history'?`<span class="pill">${readonly()?'Clase anterior · Solo lectura':'Clase de hoy'}</span>`:''}</div>${view==='student-history'?renderStudentHistory():view==='history'?renderHistory():s?renderSession():`<section class="empty"><h2>Una clase nueva, todo por hacer</h2><p>Genera la sesión de hoy con tus estudiantes y criterios.<br>Cada fecha tendrá su propio registro.</p><button class="primary large" data-action="generate">+ Generar clase de hoy</button><p class="hint">${c.criteria.map(k=>esc(k.name)).join(' · ')}</p><button data-action="criteria">Configurar criterios</button></section>`}`}
function renderHistory(){const list=[...course().sessions].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="toolbar"><h2>Tu recorrido, clase a clase</h2><p>Consulta lo registrado en cada fecha.</p></div><div class="history-list">${list.length?list.map(s=>`<button class="history-item" data-action="open-session" data-id="${s.id}"><span>${dateLabel(s.date)}<br><span class="hint">${s.students.length} estudiantes · ${s.criteria.length} criterios</span></span><span class="pill">${s.date===today()?'Hoy':'Ver clase'}</span></button>`).join(''):'<div class="empty">Todavía no hay clases registradas.</div>'}</div>`}
function cell(st,k){const s=session(),v=s.marks[st.id]?.[k.id]||'empty',info=states[v]||states.empty;return `<button class="cell ${info.cls}" data-action="mark" data-student="${st.id}" data-criterion="${k.id}" aria-label="${esc(st.name)}, ${esc(k.name)}: ${info.label}. ${readonly()?'Solo lectura':'Cambiar estado'}" ${readonly()?'disabled':''}>${info.symbol}</button>`}
function renderSession(){const s=session();studentIndex=Math.max(0,Math.min(studentIndex,s.students.length-1));return `${readonly()?'<div class="readonly">Estás consultando una clase anterior. Su registro se conserva sin cambios.</div>':''}<section class="summaries" aria-label="Progreso por criterio">${s.criteria.map(k=>{const n=s.students.filter(st=>s.marks[st.id]?.[k.id]==='yes').length;const m=s.students.filter(st=>s.marks[st.id]?.[k.id]).length;return `<div class="summary"><span>${esc(k.name)}</span><strong>${n} <small>/ ${s.students.length} logrados · ${m} marcados</small></strong><div class="bar"><span style="width:${s.students.length?n/s.students.length*100:0}%"></span></div></div>`}).join('')}</section><div class="row toolbar"><div class="legend"><span><b class="good">✓</b>Logrado</span><span><b class="progress">~</b>En proceso</span><span><b class="no">✕</b>No logrado</span><span>○ Sin marcar</span></div>${!readonly()?'<button data-action="add-criterion">+ Agregar criterio</button>':''}</div>${view==='student'?renderStudent():`<div class="grid-wrap"><table style="min-width:${250+s.criteria.length*190}px"><thead><tr><th scope="col">Estudiantes</th>${s.criteria.map(k=>`<th scope="col">${readonly()?esc(k.name):`<button class="head-edit" data-action="edit-criterion" data-id="${k.id}" title="Editar criterio y estados">${esc(k.name)} <span aria-hidden="true">⋯</span></button>`}</th>`).join('')}</tr></thead><tbody>${s.students.map((st,i)=>`<tr><td><span class="number">${String(i+1).padStart(2,'0')}</span><button class="student-name" data-action="student-history" data-id="${st.id}" aria-label="Ver historial de ${esc(st.name)}">${esc(st.name)}</button></td>${s.criteria.map(k=>`<td>${cell(st,k)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}<p class="footnote">${readonly()?'Registro conservado de esta fecha.':'Toca una casilla para cambiar su estado. Los cambios se guardan automáticamente.'}</p>`}
function renderStudent(){const s=session(),st=s.students[studentIndex];if(!st)return '<div class="empty">Esta clase no tiene estudiantes.</div>';return `<section class="student-panel"><div class="row"><div><div class="eyebrow">Estudiante ${studentIndex+1} de ${s.students.length}</div><h2>${esc(st.name)}</h2></div><div class="actions"><button data-action="student-history" data-id="${st.id}">Ver historial</button><button data-action="previous" ${studentIndex===0?'disabled':''}>Anterior</button><button data-action="next" ${studentIndex===s.students.length-1?'disabled':''}>Siguiente</button></div></div><div class="student-marks">${s.criteria.map(k=>`<div class="student-mark"><strong>${esc(k.name)}</strong>${cell(st,k)}</div>`).join('')}</div></section>`}
function newCourse(){dialog('Crear un curso',`<label for="course-name">Nombre del curso</label><input id="course-name" name="name" type="text" placeholder="Ej. 3° B" maxlength="80" required><label for="names">Estudiantes</label><textarea id="names" name="names" placeholder="Amanda González\nBenjamín Rojas\nCatalina Soto" required></textarea><div class="hint">Pega un nombre por línea. También puedes separar con punto y coma.</div>`,f=>{const names=String(f.get('names')).split(/[\n;]+/).map(n=>n.trim()).filter(Boolean),name=String(f.get('name')).trim();if(!name||!names.length)return formError('Escribe el nombre del curso y al menos un estudiante.');const c={id:uid(),name,students:names.map(name=>({id:uid(),name})),criteria:defaults(),sessions:[]};db.courses.push(c);courseId=c.id;sessionId=null;view='grid';save();modal.close();render()})}
function generate(){const c=course();if(!c.students.length){toast('Agrega al menos un estudiante al curso.');return}let s=c.sessions.find(s=>s.date===today());if(!s){s={id:uid(),date:today(),students:copy(c.students),criteria:copy(c.criteria),marks:{}};c.sessions.push(s);save()}sessionId=s.id;view='grid';studentIndex=0;render()}
function editCourse(){const c=course();dialog('Editar curso',`<label for="edit-name">Nombre del curso</label><input id="edit-name" type="text" name="name" value="${esc(c.name)}" maxlength="80" required><label>Estudiantes</label><div id="student-edits">${c.students.map(st=>`<div class="edit-student" data-id="${st.id}"><input type="text" value="${esc(st.name)}" aria-label="Nombre del estudiante" required><button type="button" class="danger" data-remove aria-label="Quitar estudiante">✕</button></div>`).join('')}</div><label for="extra-names">Agregar estudiantes</label><textarea style="min-height:100px" id="extra-names" name="extra" placeholder="Un nombre por línea"></textarea><p class="hint">Estos cambios se usarán en las próximas clases. Las sesiones ya creadas conservan sus nombres y registros.</p>`,f=>{const name=String(f.get('name')).trim();const students=[...modal.querySelectorAll('.edit-student')].map(el=>({id:el.dataset.id,name:el.querySelector('input').value.trim()}));students.push(...String(f.get('extra')).split(/[\n;]+/).map(x=>x.trim()).filter(Boolean).map(name=>({id:uid(),name})));if(!name||!students.length||students.some(s=>!s.name))return formError('Incluye un nombre de curso y al menos un estudiante con nombre.');c.name=name;c.students=students;save();modal.close();render()});modal.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>b.closest('.edit-student').remove())}
function criteriaMenu(){dialog('Criterios del curso',`<div class="history-list">${course().criteria.map(k=>`<button type="button" data-edit="${k.id}">${esc(k.name)} · Editar</button>`).join('')}<button type="button" data-add>+ Agregar criterio</button></div><p class="hint">Se usarán al generar nuevas clases.</p>`,()=>modal.close());modal.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{modal.close();editCriterion(b.dataset.edit,true)});modal.querySelector('[data-add]').onclick=()=>{modal.close();editCriterion(null,true)}}
function editCriterion(id,courseOnly=false){if(!courseOnly&&readonly())return;const target=courseOnly?course():session()||course(),existing=target.criteria.find(k=>k.id===id);dialog(existing?'Editar criterio':'Agregar criterio',`<label for="criterion-name">Nombre del criterio</label><input id="criterion-name" name="name" type="text" maxlength="80" required value="${esc(existing?.name||'')}" placeholder="Ej. Trabajo en clase"><label>Estados disponibles</label>${['yes','part','no'].map(v=>`<label class="check"><input type="checkbox" name="states" value="${v}" ${(!existing||existing.states.includes(v))?'checked':''}><span>${states[v].symbol} ${states[v].label}</span></label>`).join('')}<p class="hint">El estado vacío siempre está disponible. El orden es ✓, ~, ✕. Se aplicará a ${target===course()?'las próximas clases':'esta clase y a las próximas'}.</p>${existing?'<button type="button" class="danger" id="delete-criterion">Eliminar criterio</button>':''}`,f=>{const name=String(f.get('name')).trim(),allowed=['yes','part','no'].filter(v=>f.getAll('states').includes(v));if(!name||!allowed.length)return formError('Escribe un nombre y selecciona al menos un estado.');if(existing&&target.marks&&Object.values(target.marks).some(m=>m[id]&&!allowed.includes(m[id])))return formError('Ese estado ya tiene registros. Cambia primero las casillas que lo usan antes de quitarlo.');const k={id:existing?.id||uid(),name,states:allowed};if(existing)target.criteria=target.criteria.map(x=>x.id===id?k:x);else target.criteria.push(k);if(target!==course()){const ci=course().criteria.findIndex(x=>x.id===k.id);if(ci>=0)course().criteria[ci]=copy(k);else course().criteria.push(copy(k))}save();modal.close();render()});const del=modal.querySelector('#delete-criterion');if(del)del.onclick=()=>{if(target.criteria.length===1)return formError('Conserva al menos un criterio.');if(target.marks&&Object.values(target.marks).some(m=>m[id]))return formError('Este criterio tiene registros. Vacía sus casillas antes de eliminarlo.');target.criteria=target.criteria.filter(k=>k.id!==id);if(target!==course()&&course().criteria.length>1)course().criteria=course().criteria.filter(k=>k.id!==id);save();modal.close();render()}}
function mark(stId,kId){const s=session();if(!s||readonly())return;const k=s.criteria.find(k=>k.id===kId);if(!k||!s.students.some(st=>st.id===stId))return;const seq=['empty',...k.states],current=s.marks[stId]?.[kId]||'empty',next=seq[(seq.indexOf(current)+1)%seq.length];s.marks[stId]??={};if(next==='empty')delete s.marks[stId][kId];else s.marks[stId][kId]=next;save();const scroll=app.querySelector('.grid-wrap'),pos=scroll?{top:scroll.scrollTop,left:scroll.scrollLeft}:null;render();if(pos){const el=app.querySelector('.grid-wrap');el.scrollTop=pos.top;el.scrollLeft=pos.left}app.querySelector(`[data-student="${stId}"][data-criterion="${kId}"]`)?.focus({preventScroll:true})}
app.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;if(window.AulaCloud && !window.AulaCloud.canEdit()){toast('Resuelve el guardado pendiente antes de editar.');return;}switch(b.dataset.action){case'new-course':newCourse();break;case'home':courseId=null;sessionId=null;projection=false;render();break;case'open-course':courseId=b.dataset.id;sessionId=course().sessions.find(s=>s.date===today())?.id||null;view='grid';render();break;case'generate':generate();break;case'edit-course':editCourse();break;case'view':view=b.dataset.view;render();break;case'open-session':sessionId=b.dataset.id;view='grid';studentIndex=0;render();break;case'add-criterion':editCriterion(null);break;case'edit-criterion':editCriterion(b.dataset.id);break;case'criteria':criteriaMenu();break;case'mark':mark(b.dataset.student,b.dataset.criterion);break;case'previous':studentIndex--;render();break;case'next':studentIndex++;render();break;case'retry':save();render();break;case'project':projection=!projection;render();try{if(projection&&!document.fullscreenElement)await document.documentElement.requestFullscreen();else if(!projection&&document.fullscreenElement)await document.exitFullscreen()}catch{}break}});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&projection){projection=false;render()}});
window.addEventListener('storage',e=>{if(window.AulaCloud){window.AulaCloud.receiveStorage(e);return;}if(e.key===KEY){try{const next=JSON.parse(e.newValue);if(next?.version===1&&Array.isArray(next.courses)){db=next;saveFailed=false;render();toast('Registros actualizados desde otra pestaña.')}}catch{}}});
render();

// Optional browser integration; unsupported browsers use the normal interface.
if (document.modelContext?.registerTool) {
  const lifecycle = new AbortController();
  try {
    Promise.resolve(document.modelContext.registerTool({
      name: 'open_course',
      title: 'Abrir un curso',
      description: 'Abre un curso existente por su nombre exacto. No crea clases ni modifica registros.',
      inputSchema: {type:'object',properties:{name:{type:'string'}},required:['name'],additionalProperties:false},
      annotations: {readOnlyHint:true,untrustedContentHint:true},
      execute(input) {
        if(window.AulaCloud && !window.AulaCloud.canEdit()) throw new Error('Inicia sesión y carga tus cursos antes de continuar.');
        if (!input || typeof input.name !== 'string' || Object.keys(input).some(k=>k!=='name')) throw new Error('Indica el nombre exacto del curso.');
        const matches = db.courses.filter(c=>c.name===input.name);
        if(matches.length!==1) throw new Error('No se encontró un curso único con ese nombre.');
        courseId=matches[0].id;
        sessionId=course().sessions.find(s=>s.date===today())?.id||null;
        view='grid'; render();
        return {name:course().name,students:course().students.length,hasSessionToday:!!sessionId};
      }
    },{signal:lifecycle.signal})).catch(()=>{});
  } catch {}
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
